swagger: "2.0"

info:
  title: OAuth Example
  version: "1.0"

paths:
  /secret:
    get:
      summary: Return secret string
      operationId: app.get_secret
      responses:
        200:
          description: secret response
          schema:
            type: string
      security:
        # enable authentication and require the "email" scope for this endpoint
        - oauth2: ['email']
  /greeting:
    get:
      summary: Greeting, reponse hello message
      operationId: app.get_greeting
      responses:
        200:
          description: response
          schema:
            type: string
      security:
      # enable authentication and require the "email" scope for this endpoint
      - oauth2: ['email']

  /public:
    get:
      summary: Requires no authentication
      operationId: app.get_public
      responses:
        200:
          description: response
          schema:
            type: string
      security:
      # enable authentication and require the "email" scope for this endpoint
      - oauth2: ['email']

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    x-tokenInfoFunc: app.token_info
    scopes:
      uid: Unique identifier of the user accessing the service.
